### ISSUE TITLE
Jetpack Dependencies: Make admin notification truly dismissible

### ISSUE THREAD

**Issue by alaczek** [Automattic/theme-tools#14]
While it's possible to close the admin notification, it keeps coming back on page refresh, so it's not truly dismissible.
Reported here: https://themes.trac.wordpress.org/ticket/28319#comment:24

**Comment by kathrynwp** [comment]
Also reported here: https://wordpress.org/support/topic/the-jetpack-plugin-is-required-to-use-some-of-this-theme’s-features

**Comment by sarahblackstock** [comment]
Also here: https://wordpress.org/support/topic/disable-jetpack-notification-in-sela?replies=1

**Comment by kathrynwp** [comment]
This function in a child theme is a workaround for hiding the dashboard notices:

```
function removeThat() {
    remove_action( 'admin_head', array( 'Sela_Theme_Plugin_Enhancements', 'init' ) );
}
add_action( 'admin_head', 'removeThat', 1 );
```

Props @laurelfulford

**Comment by jeffikus** [comment]
@kathrynwp i didn't get to this this week unfortunately, i can try take a look on Monday?

**Comment by jeffikus** [comment]
@kathrynwp sorry man, i've had no time to tackle this this week :( has anyone else managed to take a look?

**Comment by sarahmonster** [comment]
The solution here would be to use some JS to save a theme option, and then to check for that option prior to showing the notification. 

There's some conversation & suggestions for implementation here that may be useful: https://make.wordpress.org/core/2015/04/23/spinners-and-dismissible-admin-notices-in-4-2/:

> The second path, for notices that persist across different page loads, is to bind to the click event on the .notice-dismiss element in your own notice and trigger whatever it is your plugin may need to do to remember that the notice has been dismissed, such as storing a site or user option using Ajax. A note of caution that in an ideal scenario, core would eventually provide a framework for persistently dismissible notices that are not tied to query args, so be prepared for future changes if you choose to use this method.
