### ISSUE TITLE
.org submitter: Remove headstart directory

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/theme-tools#19]
Noticed while re-submitting Pique:
https://themes.trac.wordpress.org/changeset?old_path=pique/1.2.4&new_path=pique/1.2.5

It looks like annotations for Headstart are being stored in the `inc/headstart` directory. Since these are .com specific, they should be removed for .org submission.

**Comment by sixhours** [comment]
The above patch seems to work for me, but I would love an extra set of eyes and some testing on this before merging. Thank you!

**Comment by alaczek** [comment]
Works as expected. Merged!
