### ISSUE TITLE
instructions are unclear: plugin-enhancements.js should be included too

### ISSUE THREAD

**Issue by senlin** [Automattic/theme-tools#32]
The instructions on how to use this are unclear and it seems that Automattic's very own theme developers have difficulty using it correctly. 
They only go as far as to require the PHP script.

The `plugin-enhancements.js` file however takes care of remembering a user's decision to clicking the warning message away.

As an example, the [Pique theme](https://wordpress.org/themes/pique/) by Automattic for some reason does not include the js file and therefore a user can keep clicking the warning (in a child theme), it will always come back.

**Comment by laurelfulford** [comment]
Thanks for submitting this issue, @senlin!

It looks like the current version of Pique (https://themes.svn.wordpress.org/pique/1.2.12/inc/) now does include the plugin-enhancements.js. It is added automatically along with the PHP file.

I suspect there was a delay in us updating the version of the theme in the WordPress.org repo after updates were made to this generator. That would cause the theme not to have this JavaScript file for a while, even though it was added to other themes.

I'm going to close this issue; if you think it should remain open please let us know!

**Comment by senlin** [comment]
Wow, 8 months after I opened this issue, it receives its first response!
I'm truly impressed...
