### ISSUE TITLE
.org Submitter: Sketch outputs without tags in style.css

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/theme-tools#9]
When running Sketch through the script, the tags don't get re-added to style.css header. 

This can be tested by running through the script step-by-step to see where it's getting thrown off; there's likely just a formatting issue with the reges, where Sketch is using *s before each line in the style.css header. 

I've tested a few other themes that use this style (there are fifteen in total, all older themes) and they all have the same issue. Either the themes should be adjusted to use a consistent style, or the regex used by the script should be adjusted to be more robust. (Will require testing!)

**Comment by iamtakashi** [comment]
I've just experienced this with Sorbet now and I agree that theme needs to be adjusted.

So, if you experienced this cleanup the header like the following before building a zip in MC.

```
/*
Theme Name: Twenty Sixteen
Theme URI: https://wordpress.org/themes/twentysixteen/
Author: the WordPress team
Author URI: https://wordpress.org/
Description: Twenty Sixteen is a modernized take on an ever-popular WordPress layout — the horizontal masthead with an optional right sidebar that works perfectly for blogs and websites. It has custom color options with beautiful default color schemes, a harmonious fluid grid using a mobile-first approach, and impeccable polish in every detail. Twenty Sixteen will make your WordPress look beautiful everywhere.
Version: 1.2
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Tags: black, blue, gray, red, white, yellow, dark, light, one-column, two-columns, right-sidebar, fixed-layout, responsive-layout, accessibility-ready, custom-background, custom-colors, custom-header, custom-menu, editor-style, featured-images, flexible-header, microformats, post-formats, rtl-language-support, sticky-post, threaded-comments, translation-ready
Text Domain: twentysixteen
*/
```

I'm closing this as the tool works as expected.
